# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: vixl.vixl
PackageVersion: 0.10.17
InstallerType: nullsoft
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: /S
  SilentWithProgress: /S
UpgradeBehavior: install
ReleaseDate: 2026-09-25
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/vixl-ai/vixl/releases/download/v0.10.17/vixl_0.10.17_x64-setup.exe
  InstallerSha256: F5E9EA47087708A2D4AE8190F100EAEC134301BAA9B792B6895BFB358B015554
ManifestType: installer
ManifestVersion: 1.12.0
